#!/bin/sh

if test -x extlib/fxt/bootstrap ; then
   cd extlib/fxt && ./bootstrap ; cd -
fi

cd extlib/gtg && autoreconf -vfi ; cd -

cd extlib/opari2/build-frontend && autoreconf -vfi ; cd -

autoreconf -vfi
