--- linux-2.6.12-rc2-orig/arch/i386/kernel/Makefile	2005-04-04 18:38:04.000000000 +0200
+++ linux-2.6.12-rc2-fkt/arch/i386/kernel/Makefile	2005-05-21 01:11:02.291261750 +0200
@@ -12,6 +12,9 @@ obj-y	:= process.o semaphore.o signal.o 
 obj-y				+= cpu/
 obj-y				+= timers/
 obj-$(CONFIG_ACPI_BOOT)		+= acpi/
+ifdef CONFIG_FKT
+obj-y				+= fkt_header.o
+endif
 obj-$(CONFIG_X86_BIOS_REBOOT)	+= reboot.o
 obj-$(CONFIG_MCA)		+= mca.o
 obj-$(CONFIG_X86_MSR)		+= msr.o
