#define NM      "/usr/bin/nm -B"
#define AWK     "gawk"
#define SCRIPT  "/usr/local/bin/pomp2-parse-init-regions.awk"
#define EGREP   "/bin/grep -E"
#define VERSION "1.0.2"
#define POMP2_API_VERSION "1.0.2"
#define CFLAGS  "-I/usr/local/include"
